repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix","--ignore","E402,F401,F841,E701,E702,E722,E731,E741"]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: []
  - repo: local
    hooks:
      - id: root-hygiene
        name: Root hygiene policy check
        entry: python3 scripts/root_hygiene_check.py
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: requirements-all-sort
        name: Ensure requirements-all.txt sorted unique
        entry: bash -c 'sort -u requirements-all.txt -o requirements-all.txt && git add requirements-all.txt'
        language: system
        files: ^requirements-all\.txt$
        stages: [pre-commit]
