services:
  backend:
    build:
      context: .
    container_name: zenglow-backend
    env_file:
      - .env
    environment:
      STRICT_ENV: "false"
      DEV_FAKE_LLM: ${DEV_FAKE_LLM:-true}
      RAG_RETRIEVAL_MODE: ${RAG_RETRIEVAL_MODE:-disabled}
      DATABASE_URL: ${DATABASE_URL:-sqlite:///./dev.db}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Allow backend to reach the ollama service by container name when outbound restrictions active
      LLM_ALLOW_PREFIXES: "http://ollama:"
      OLLAMA_URL: http://ollama:11434
      OLLAMA_MODEL: "gemma:2b"
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    # Host port 11434 already in use by a host-level ollama (PID 4083); map to 11435 externally.
    ports:
      - "11435:11434"
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      OLLAMA_API_BASE_URL: http://ollama:11434
    ports:
      - "3000:8080"
    volumes:
      - webui_data:/app/backend/data

  redis:
    image: redis:7-alpine
    container_name: zenglow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  ollama_models:
  webui_data:
