[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
disable_error_code = "attr-defined"

[[tool.mypy.overrides]]
module = ["fastapi.*", "pydantic.*", "redis", "msgpack", "psycopg2", "app.health.system_metrics", "prometheus_client"]
ignore_missing_imports = true

[tool.ruff]
select = ["E", "F", "I", "B"]
line-length = 100
target-version = "py311"
exclude = [".venv", "build", "dist"]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
